package ufrpe.sbpc.botpcd.entity

enum class AssistanceType {
    LIBRAS_MONITOR,
    MOBILITY_MONITOR,
    NEURODIVERGENT_WELCOME_MONITOR,
    AUDIO_DESCRIPTION_PROFESSIONAL,
    LIBRAS_INTERPRETER_PROFESSIONAL
}